name: Ubuntu reference generation

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
    main:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            subdir: [short-tests, medium-tests, long-tests, valid-adq, valid-bind, valid-complex, valid-defaillance, valid-draft, valid-filter-outputs, valid-hydro, valid-hydroBind, valid-hydroPricing, valid-marginCost, valid-parallel, valid-thermal, valid-ts-gen-export]

        steps:
        - name: Get release
          id: get_release
          uses: bruceadams/get-release@v1.2.3

        - name: Checkout self
          uses: actions/checkout@v2

        - name: zip directory
          run: zip -r output.zip ${{ matrix.subdir }}

        - name: Upload .zip
          uses: actions/upload-release-asset@v1.0.2
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: output.zip
            asset_name: ${{ matrix.subdir }}-${{ steps.get_release.output.tag_name }}.zip
            asset_content_type: application/octet-stream
